# Generated by Django 5.0.5 on 2024-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_quarto_foto_quarto'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='titulo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
