# Generated by Django 5.0.5 on 2024-05-16 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('tipo_quarto', models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASAL', 'Casal'), ('CONFORT', 'Confort'), ('LUXO', 'Luxo')], max_length=15)),
                ('data_reserva', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASAL', 'Casal'), ('CONFORT', 'Confort'), ('LUXO', 'Luxo')], max_length=15)),
                ('disponibilidade', models.IntegerField()),
                ('valor', models.FloatField(max_length=9999)),
                ('descricao', models.TextField(max_length=255)),
                ('data_reserva', models.DateTimeField(default=datetime.datetime.now)),
                ('foto_quarto', models.ImageField(upload_to='quartos/')),
            ],
        ),
    ]
