# Generated by Django 5.0.5 on 2024-05-16 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_reserva',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
